### ISSUE TITLE
Get-Module does not pick up community 

### ISSUE THREAD

**Issue by jdansak** [raymix/PowerShell-UDLauncher#1]
`($null -eq (Get-Module -Name UniversalDashboard -ListAvailable))` needs to be changes to 

`($null -eq (Get-Module -Name UniversalDashboard* -ListAvailable)) `  or ` ($null -eq (Get-Module -Name UniversalDashboard -ListAvailable)) -or ($null -eq (Get-Module -Name UniversalDashboard.Community -ListAvailable))  `

**Comment by raymix** [comment]
Thanks for the heads up and a solution, @Jdansak 
I got a fresh computer to test community edition on, there shouldn't be any more issues now.
